### ISSUE TITLE
Mobile bugs:

### ISSUE THREAD

**Issue by lovise-hub** [oslopride/oslopride.no#125]
Articles page:
- Too much padding around tekst in box. Use 1.5rem.

Responsive menu:
- Use padding-left:0rem; Instead of 2rem on the left of the menulinks.

Frontpage - Articles:
- Heading: "Viktige intervju, rørende...." Use font-size: 2rem;
- Remove margin on article boxes. 

Fontpage - Partners:
The logo for Fri Oslo og Akershus is a bit small on mobile.

**Comment by sarahfossheim** [comment]
Closing this because split up in separate issues :)
