### ISSUE TITLE
Desktop bugs

### ISSUE THREAD

**Issue by lovise-hub** [oslopride/oslopride.no#126]
Partnere:
- The line-height on the content-text is to small. Use same as other pages
- The hero/topbanner is not the same as the other pages. 

Om oss:
- More space under content

Kontakt:
- More space under content

Hero/topbanner on all pages:
- More line-height on the paragraph-text under the page-title

Links:
- Do the color have to be bright blue? Can we change to the dark purple color. And also. We have to add an underline to the links so that it follows the Accessibility Guidelines (Universell utforming). 

Footer:
- Need underline on links here as well. Also they need a hover color. Just use: #E350A0 
- More line-height on the text and links here as well

**Comment by sarahfossheim** [comment]
Closing this because split up in separate issues
