### ISSUE TITLE
Perhaps the header should be part of the page, and not a block?

### ISSUE THREAD

**Issue by boyeborg** [oslopride/oslopride.no#14]
Every page should have a header, perhaps that should be part of the page, and not an optional block?

The schema for a page might then look something like this:

```
...

title: "Page",
name: "page",
type: "document",
fields: [
  {
    title: "Title",
    name: "title",
    type: "locale_page_title"
  },
  {
    title: "URL",
    name: "slug",
    type: "slug",
    options: {
      source: `title.${getDefaultLanguage().id}`
    }
  },
  {
    title: "Color",
    name: "color",
    type: "string",
    options: {
      list: [
        { title: "Blue", value: "#3399ff" },
        { title: "Green", value: "#2cb028" },
        ...
      ]
    }
  },
  {
    title: "Blurb",
    name: "blurb",
    type: "text_area"
  },
  {
    title: "Image",
    name: "image",
    type: "image"
  },
  {
    title: "Blocks",
    name: "blocks",
    type: "locale_blocks"
  }
],

...
```

Illustration:

<img width="1440" alt="Skjermbilde 2020-01-18 kl  11 37 34" src="https://user-images.githubusercontent.com/6630430/72662476-eb87de00-39e7-11ea-9327-fb45443c21bd.png">

**Comment by KarlGe** [comment]
Not every page will have the same type of header, though, for example a listing page only has a title (and a color I assume) in the current sketches
![Screenshot_20200118_121724_org mozilla firefox](https://user-images.githubusercontent.com/3405524/72662909-cf3a7000-39ec-11ea-9584-d06d1824f040.png)

That could be solved in multiple ways though, it could be cool to have a dropdown of available "page types" and that would reveal the necessary fields to fill out.

**Comment by boyeborg** [comment]
@KarlGe That's true! I didn't think of that. But perhaps the above page could be the way we render a page without an image? That could also backfire, with yielding very complex rendering logic. So maybe a dropdown would be better, as you suggest. But then, maybe it's fine having it as a block.
