### ISSUE TITLE
Update Hero component design

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#177]
- Remove the angle
- Increase font-size on heading to 72px
- Updated hero on all pages it is used

![image](https://user-images.githubusercontent.com/435283/106653984-d13f8480-6597-11eb-8a40-12298eb2059f.png)

**Comment by luk-str** [comment]
I'd be happy to take care of this if that's cool 🌈

**Comment by hexjelly** [comment]
Please, have at it! 😀

I haven't thought too much about how to best do this, and whether it makes sense to have the anchor link be a part of the hero component (as an optional prop with a URL?), or whether it makes more sense to have it be on the page itself (not part of the hero component at all) 🤷‍♀️ Any suggestion would be welcome.

**Comment by luk-str** [comment]
Cool, I'll look into it!

**Comment by luk-str** [comment]
@hexjelly Just some questions to clarify 😊

1. What should the arrow button link to? Where does it take us? 🐎
2. Do we want the heading on front page at 72px as well? It's currently slightly bigger than the headings on the other pages (3rem vs 2.5rem).

Thanks! 🤙

**Comment by hexjelly** [comment]
1. This is why I'm unsure where it belongs (though if I remember correctly, the Hero component is used on every page template so it's probably fine that the option is inside the component..?). The button should take you down to the nearest content basically. I believe the intention/use was mostly for mobile since the hero would cover most of the initial screen.

So most likely a `<a href="#something">` type of thing. Or maybe a function that gets a ref to the hero and scrolls down the page enough to move it out of the view. I'm not sure the implementation matters too much as long as it makes sense and is accessible in some way. And maybe there's something better?

2. Uuuuhm yes... I think (??). It's probably different because we have been bad at keeping styles consistent :) @lovise-hub can correct me if I'm wrong with the design

**Comment by luk-str** [comment]
Alright, got it, thanks!
Yeah, the hero component seems to appear on every page and it's unlikely the button would be used elsewhere outside the hero component so it's probably best to keep it inside the component itself 👍
