### ISSUE TITLE
Add new content-block on font-page

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#178]
There should be a new text section between hero and first "CTA" block

![image](https://user-images.githubusercontent.com/435283/106654101-f8965180-6597-11eb-86b2-da71f153fa7c.png)

**Comment by luk-str** [comment]
I can take care of this 👋
Although it'd be awesome to get the PRs for the header changes reviewed first 🙌

**Comment by hexjelly** [comment]
Please feel free! :)
