### ISSUE TITLE
Remove the line from the sub-heading

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#180]
Remove the subheading leading lines (might be scattered around a bit in the code 😬)

![image](https://user-images.githubusercontent.com/435283/106654563-925dfe80-6598-11eb-95fd-71b7bce65cc6.png)

**Comment by luk-str** [comment]
Hey, I see where it is, will be a quick fix. Mind if I jump on this? 🐬

**Comment by hexjelly** [comment]
Great 🤩

I'm unsure whether this styling is repeated in different places, or whether someone has been good and just made a reuseable component. So maybe take a quick look around to make sure it's removed everywhere in that case so we limit some dead code, that would be great :)

**Comment by luk-str** [comment]
Sure, will do! 😊
