### ISSUE TITLE
Improved sponsor page

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#181]
![Partnere](https://user-images.githubusercontent.com/435283/116457286-7ef2c480-a863-11eb-8cd9-439674be313c.png)

**Comment by luk-str** [comment]
@hexjelly is this issue stil valid? If so, I can take care of this 👍

**Comment by hexjelly** [comment]
Yea I believe this is yet to be updated! I just edited the issue with a screenshot from the newest design sketches just so it's clear. Feel free to go for it!

**Comment by luk-str** [comment]
Cool, on it ✌️
