### ISSUE TITLE
Make frontpage hero 100vh

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#193]
Just the frontpage hero!

**Comment by luk-str** [comment]
Hey guys! 🙌

Just looked into the issue.
From my quick test here it looks like you can safely remove the [min-height property on line 8 in the hero component](https://github.com/oslopride/oslopride.no/blob/156798f3150156a691ddd3b48671f20423121014/web/src/components/hero.tsx#L8).
Any content in the hero component + it's padding already makes the height larger than 400px in all cases I could find so the property is superfluous.

Once removed from the hero component, you should be able to add min-height to [the hero css on just the front-page](https://github.com/oslopride/oslopride.no/blob/156798f3150156a691ddd3b48671f20423121014/web/src/pages/front-page.tsx#L30-L60) without it conflicting with the component's internal properties 😊

Also, on a side-note, if the idea is to have the hero image fill the front-page, then the height should probably be less than 100vh as the hero has some top and bottom padding that's added on top of the defined height ☀️
