### ISSUE TITLE
Update yarn.lock file

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#197]
Not sure what exactly is causing this, but there seems to be a problematic version of a package that is pinned by the yarn.lock file. So far we've seen 3 different people having trouble setting up the repo because of this. 

Solution would probably be just to delete the current `yarn.lock` file (and probably maybe deleting `node_modules` folder), do a `yarn install` and commit the new yarn.lock file!

**Comment by boyeborg** [comment]
Maybe we could swap yarn with npm v7 at the same time? As far as I know it should support mono repos and workspaces like yarn, but never tried it.
