### ISSUE TITLE
Update articles page design

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#200]
There's a few small changes to the article list page:

- Move content below hero
- Use the new hero scroll button option
- Create a "load more" button that will load more articles when pressed, showing a default of ... there's 3 in the design, but I imagine it's more for illustration purposes, and we probably want to load at least a few more by default?
- Date headers should use long form date names instead of just numbers

![image](https://user-images.githubusercontent.com/435283/110031837-afbcee80-7d37-11eb-9d1e-24ac3f3bc514.png)

**Comment by hexjelly** [comment]
We are already using `date-fns` on the page elsewhere, so I suggest using it to format the date with.

**Comment by hexjelly** [comment]
There's also some questions around the "load more" feature, since I'm not sure if there's any sensible way of doing pagination in Sanity queries. You could probably hack around it by keeping track of the date of the last article and making the next query get x items after that date. Then when you no longer get the amount of articles expected, you reached the end? Maybe there is a much better way?

We also don't really have a huge amount of articles, so maybe fetching the entire list with just the information necessary (slug, date, title, and summary) is totally fine? We could then just make load more be more like "show more" in reality.

**Comment by boyeborg** [comment]
> We also don't really have a huge amount of articles, so maybe fetching the entire list with just the information necessary (slug, date, title, and summary) is totally fine? We could then just make load more be more like "show more" in reality.

I think that's a good initial approach. We can fix it later if it becomes a performance issue.
