### ISSUE TITLE
Split-pane block

### ISSUE THREAD

**Issue by boyeborg** [oslopride/oslopride.no#25]
This should just allow the user to add two blocks side by side. Perhaps not all blocks should be allowed? (in the illustration bellow, two text blocks are used).

![image](https://user-images.githubusercontent.com/6630430/74099552-5f1f9580-4b25-11ea-802f-515f756ea7fd.png)

**Comment by sarahfossheim** [comment]
@boyeborg @hexjelly - I suggest we fix the conflicts and merge the PR so we can close this issue?

**Comment by hexjelly** [comment]
I pushed a fix for the conflicts, hope I didn't miss anything crazy. As long as there's still any use for it, though it is pretty basic :)
