### ISSUE TITLE
Hero component adds horizontal scrollbar

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#61]
This is fixed by setting width to use `100%` instead of `100vw` I think, as vw doesn't take scrollbars into consideration. So when the page is long enough and you get a vertical scrollbar, the hero will take up more horizontal space and you get a horizontal scrollbar.

Relevant file: `web\src\components\hero.tsx`

I'm only making this into an issue because I'm not sure if there was any specific reason to use vw instead of percentage width that I might be overlooking, that might creates issues elsewhere :)

**Comment by boyeborg** [comment]
Yeah, I've noticed that too. Lame that vw does that 👎
