### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by boyeborg** [oslopride/oslopride.no#84]
Basic SEO for the new site. It doesn't need to be super awesome, but it should look nice when sharing stuff on social media.

**Comment by christiankn** [comment]
We should also make sure it's not too far off what we already have, and that major links (including article-links) don't break.

**Comment by boyeborg** [comment]
@christiankn I think we'll be able to recreate most of the contend with the same URLs. We had the `/p/<slug>` for custom pages before, but we can just redirect `/p/<whatever> -> /<whatever>` and should be fine
